# This file contains values from Cookiecutter

default_context:
  project_name: "overhood"
  project_description: "underhood.club helper package"
  organization: "underhood.club"
  license: "Apache Software License 2.0"
  version: "0.9.0"
  github_name: "tiulpin"
  email: "hey@underhood.club"
