name: '👩‍💻 it.underhood.club weekly'

on:
  schedule:
    - cron: '0 6 * * MON'
  workflow_dispatch:
    inputs:
      first_tweet:
        description: 'From tweet (URL, will be included)'
        default: ''
        required: false
      last_tweet:
        description: 'Until tweet (URL, will not be included)'
        default: ''
        required: false

jobs:
  dump:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tiulpin/underhood
      env:
        FIRST_TWEET: ${{ github.event.inputs.first_tweet }}
        LAST_TWEET: ${{ github.event.inputs.last_tweet }}
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        UNDERHOOD: itunderhood
    steps:
      - name: Pull latest repository
        uses: actions/checkout@v2
        with:
          repository: tiulpin/itunderhood
          path: ./itunderhood
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: underhood
      - name: Push latest URLs
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
          directory: itunderhood
          repository: tiulpin/itunderhood
