name: '💼 produnderhood weekly'

on:
  schedule:
    - cron: '0 6 * * MON'
  workflow_dispatch:
    inputs:
      first_tweet:
        description: 'From tweet override (URL, will be included)'
        default: ''
        required: false
      last_tweet:
        description: 'Until tweet override (URL, will not be included)'
        default: ''
        required: false
      username:
        description: 'Author username override'
        default: ''
        required: false
      name:
        description: 'Author name override'
        default: ''
        required: false
      avatar:
        description: 'Avatar override'
        default: ''
        required: false

jobs:
  dump:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tiulpin/underhood
      env:
        FIRST_TWEET: ${{ github.event.inputs.first_tweet }}
        LAST_TWEET: ${{ github.event.inputs.last_tweet }}
        AVATAR: ${{ github.event.inputs.avatar }}
        NAME: ${{ github.event.inputs.name }}
        USERNAME: ${{ github.event.inputs.username }}
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        UNDERHOOD: produnderhood
    steps:
      - name: Pull latest repository
        uses: actions/checkout@v2
        with:
          repository: tiulpin/produnderhood
          path: ./produnderhood
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: underhood
      - name: Push latest URLs
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
          directory: produnderhood
          repository: tiulpin/produnderhood
