name: 'send 🚀 telethreads'

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  dsunderhood:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tiulpin/underhood
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        UNDERHOOD: dsunderhood
    steps:
      - name: Pull latest repo
        uses: actions/checkout@v2
        with:
          repository: tiulpin/dsunderhood
          path: ./dsunderhood
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: underhood telethread
      - name: Push latest telethreads
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
          directory: dsunderhood
          repository: tiulpin/dsunderhood

  itunderhood:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tiulpin/underhood
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        UNDERHOOD: itunderhood
    steps:
      - name: Pull latest repo
        uses: actions/checkout@v2
        with:
          repository: tiulpin/itunderhood
          path: ./itunderhood
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: underhood telethread
      - name: Push latest telethreads
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
          directory: itunderhood
          repository: tiulpin/itunderhood

  mobileunderhood:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tiulpin/underhood
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        UNDERHOOD: mobileunderhood
    steps:
      - name: Pull latest repo
        uses: actions/checkout@v2
        with:
          repository: tiulpin/mobileunderhood
          path: ./mobileunderhood
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: underhood telethread
      - name: Push latest telethreads
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
          directory: mobileunderhood
          repository: tiulpin/mobileunderhood

  produnderhood:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tiulpin/underhood
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        UNDERHOOD: produnderhood
    steps:
      - name: Pull latest repo
        uses: actions/checkout@v2
        with:
          repository: tiulpin/produnderhood
          path: ./produnderhood
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: underhood telethread
      - name: Push latest telethreads
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
          directory: produnderhood
          repository: tiulpin/produnderhood

