name: '@underhood'

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Author Twitter username'
        default: 'silyutinaolga'
        required: true
      tweet:
        description: 'The first tweet URL'
        default: 'https://twitter.com/dsunderhood/status/1351064464431443970'
        required: true

jobs:
  # stupid check to see what's underhood will be processed
  itunderhood:
    runs-on: ubuntu-latest
    if: contains( ${{ github.event.inputs.tweet }}, 'itunderhood' )
    steps:
    - run: echo "itunderhood"
  produnderhood:
    runs-on: ubuntu-latest
    if: contains( ${{ github.event.inputs.tweet }}, 'produnderhood' )
    steps:
    - run: echo "produnderhood"
  mobileunderhood:
    runs-on: ubuntu-latest
    if: contains( ${{ github.event.inputs.tweet }}, 'mobileunderhood' )
    steps:
    - run: echo "produnderhood"
  dsunderhood:
    runs-on: ubuntu-latest
    if: contains( ${{ github.event.inputs.tweet }}, 'dsunderhood' )
    steps:
    - run: echo "produnderhood"
     
  dumphood:
    name: '🗑 @dumphood'
    runs-on: ubuntu-latest
    container:
      image: tiulpin/dumphood
      env:
        AUTHOR: ${{ github.event.inputs.username }}
        TWEET: ${{ github.event.inputs.tweet }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - run: bash /entrypoint.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.username }}
          path: /dump

  topichood:
    name: '🎩 @topichood'
    needs: dumphood
    runs-on: ubuntu-latest
    container:
      image: tiulpin/topichood
    steps:
      - name: Download the latest dump
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.inputs.username }}
          path: ${{ github.event.inputs.username }}
      - run: topichood ${{ github.event.inputs.username }}

  notionhood:
    name: '📔 @notionhood'
    needs: dumphood
    runs-on: ubuntu-latest
    steps:
      - name: Download the latest dump
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.inputs.username }}
          path: dump
      - run: ls -la
